### PR TITLE
Fix support for mobile Firefox

### PR DESCRIPTION
**Pull request by k3a**
orientPortrait is not used and is probably wrongly implemented anyway.

That condition I removed was preventing swipe-to-next and swipe-to-previous actions to work in the mobile Firefox unless the device orientation was changed to another one and back before swiping.

### CODE REVIEW

**Comment by ahmednooor** [comment]
it seems to be working fine without patch on android ff v65.0.1
Screen Rec: https://streamable.com/91toy

p.s. i first wrote this when i didn't even know what return meant in a function so there is lots of awkward stuff in this code base. the orientPortrait was supposed to prevent swipe when browser is zoomed in. this was before the implementation of custom zoom. 
right now i am not very confident about removing that if condition on viewport as the viewport gets used in touch move handlers in the case browser is zoomed in. browser zoom is kind of a fallback to custom zoom. (not too confident to change anything if it works fine)
let me know your thoughts, err details etc.

thanks.

**Comment by k3a** [comment]
Thanks for testing it, maybe I should have been more clear about how to reproduce it or why it happens so I made a test page now, based on my original page I use halkaBox on. Please have a look: https://k3a.me/u/halkabug/

You click on the first image and then use finger to swipe to another one. That works in Chrome and using arrow keys on pc.

But it won't work on mobile Firefox 66.0.2, android 9. The swipe is not registered because viewport doesn't match window.innerWidth at the time touch end is called.

Maybe it is also related to the page viewport being 800. But simply setting viewport on every touch start fixed it for me.

What do you think?

**Comment by ahmednooor** [comment]
Thanks for explaining.

So I was able to reproduce the problem. It seems, the `content="width=..."` in viewport meta tag is causing the problem as you pointed out. When it is replaced with the default responsive one (which is on the demo page), it works fine.

The `window.innerWidth` changes when lightbox specific html gets appended to body. which is why the swipe fails in `touchMove` as it checks `window.innerWidth === viewport`.

I am still not confident enough to remove the orientPortrait because it prevents the swipe when browser is natively zoomed in by the user which is kind of a fallback to custom zoom. (I might remove it in the future because sometimes the user zooms in for legibility only and not for zooming the image. In which case user should be able to swipe. I am just not too confident right now.)

So what I did was, I updated the `viewport = window.innerWidth` in `open(...)` function. So whenever lightbox specific html is displayed, the `viewport` gets updated to the current `innerWidth`.

I am attaching my version of `halkaBox.js` in a zip below. Let me know what you think.

Also give me 2~3 days to finalize about the pull request. Then we will merge it with either orientPortrait removed or with viewport update only.

Thanks.

[halkaBox.zip](https://github.com/ahmednooor/halkaBox.js/files/3144297/halkaBox.zip)

**Comment by k3a** [comment]
Setting viewport like this is acceptable for me as well. So feel free to fix it this way if you want / you may then close the pull request if you handle it differently. Thanks for looking into the problem! 

I use halka for camera archive and it makes browsing photos quick (after disabling css animations and transitions though :P but that's easy to do and I like how lightweight the library otherwise is).

**Comment by ahmednooor** [comment]
Thanks. I patched it my way. 
https://github.com/ahmednooor/halkaBox.js/commit/7a599e2852acfe9e2b91cbe71c4f8fc24150501d

Thanks for pointing out the error :)
Closing this now.

**Pull request closed without merging**
